#!/bin/sh

CVSGROUP=cvsusers

choose_chgrp_and_chmod()
{
  clgroup=`ls -Lld $CL_DIR | awk '{print($4)}'`
  if test "$clgroup" = "$CVSGROUP"; then
    CHGRP=chgrp
    CHMOD=chmod
  else
    CHGRP=true
    CHMOD=true
  fi
}

get_arch()
{
  case `uname -m` in
    *86*)        echo x86   ;;
    sun*|sparc)  echo sparc ;;
    *)           echo error ;;
  esac
}

get_os()
{
  case `uname -s` in
    Linux|linux)  echo linux    ;;
    SunOS)        echo solaris  ;;
    *)            echo error ;;
  esac
}

choose_chgrp_and_chmod
ARCH=`get_arch`-`get_os`
SOURCE=`pwd`
cd $CL_DIR


# Установка/обновление rules.cvslvk для PCCTS
WINAME='pccts_'$ARCH'-1.33MR12b'
if test -d $WINAME; then
  cp $SOURCE/rules.cvslvk.pccts $WINAME/rules.cvslvk
  touch $WINAME/NOREMOVE
  $CHGRP $CVSGROUP $WINAME/*
  $CHMOD g+rw $WINAME/*
fi

# Создание псевдомодуля lexyacc
WINAME='lexyacc_'$ARCH
mkdir $WINAME
cp $SOURCE/rules.cvslvk.lexyacc $WINAME/rules.cvslvk
touch $WINAME/REMOVE_ON_CVSLVK_UPDATE
$CHGRP $CVSGROUP $WINAME/* $WINAME
$CHMOD g+rw $WINAME/* $WINAME

# Создание псевдомодулей для d99
# Отличаются параметром (mtfloat,mtdouble,mtint) и зависят от d99-libmon
# с тем же параметром и от mmt
if ls -d 'd99-mmt_'$ARCH''* >/dev/null 2>/dev/null; then
  for mt in mtfloat mtdouble mtint; do
    if ls -d 'd99-libmon_'$ARCH''*''$mt''* >/dev/null 2>/dev/null; then
      WINAME='d99_'$ARCH'-'$mt
      mkdir $WINAME
      echo d99-mmt > $WINAME/depend.cvslvk
      echo d99-libmon_$mt >> $WINAME/depend.cvslvk
      touch $WINAME/REMOVE_ON_CVSLVK_UPDATE
      $CHGRP $CVSGROUP $WINAME/* $WINAME
      $CHMOD g+rw $WINAME/* $WINAME
    fi
  done
fi

# Cоздание псевдомодуля для X11
# Sun-овские include-файлы из /usr/openwin/include не определяют типы,
#   возвращаемые функицями, из-за чего g++ ругается
# Создаем workaround. На платформе linux ставим WI для совместимости
WINAME='X_'$ARCH
mkdir $WINAME
touch $WINAME/REMOVE_ON_CVSLVK_UPDATE
if test `get_os` = solaris; then
  echo 'override INCLUDES += -I$(CL_WI)/include -I/usr/openwin/include' > $WINAME/rules.cvslvk
  echo 'override LDFLAGS += -L/usr/openwin/lib -lX11' >> $WINAME/rules.cvslvk
  mkdir -p $WINAME/include/X11
  for i in Xlib.h Xutil.h Xresource.h; do
    test -f /usr/openwin/include/X11/$i && sed 's/extern[ \t]*\(X[a-zA-Z0-9_]*[ \t]*(\)/extern int \1/' </usr/openwin/include/X11/$i >$WINAME/include/X11/$i
  done
  mkdir -p $WINAME/include/X11/ICE
  test -f /usr/openwin/include/X11/ICE/ICElib.h && sed 's/extern[ \t]*\(I[a-zA-Z0-9_]*[ \t]*(\)/extern int \1/' </usr/openwin/include/X11/ICE/ICElib.h >$WINAME/include/X11/ICE/ICElib.h
else
  echo 'override INCLUDES += -I/usr/X11R6/include' > $WINAME/rules.cvslvk
  echo 'override LDFLAGS += -L/usr/X11R6/lib -lX11' >> $WINAME/rules.cvslvk
fi
$CHMOD g+rw `find $WINAME -print`
$CHGRP $CVSGROUP `find $WINAME -print`
