#!/bin/sh
set -e

CVSGROUP=stand

create_wi()
{
	local WINAME="$1"
	mkdir "$WINAME"
	touch "$WINAME"/REMOVE_ON_CVSLVK_UPDATE
	touch "$WINAME"/NOREMOVE
}

create_link()
{
	local TARGET="$1"
	local LINK="$2"
	if [ -e "$TARGET" ]; then
		ln -s "$TARGET" "$LINK"
	else
		echo "Warning: $TARGET not found." >&2
	fi

}

create_links()
{
	local TARGET="$1"
	shift 1

	test -d "$TARGET" || mkdir "$TARGET"
	for FILE in "$@"; do
		create_link "$FILE" "$TARGET/$(basename "$FILE")"
	done

}


chmod_wi()
{
	WINAME="$1"
	clgroup=$(ls -Lld "$CL_DIR" | awk '{print($4)}')
	test "$clgroup" = "$CVSGROUP"||return 0
	chgrp -R "$CVSGROUP" "$WINAME"
	chmod -R g+rw "$WINAME"
}

# Создание псевдомодуля pccts
install_pccts()
{
	WINAME='pccts_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.pccts" "$WINAME/rules.cvslvk"
	cp "$SOURCE/convgen.sed" "$WINAME"
	create_links "$WINAME/bin" /usr/bin/antlr /usr/bin/dlg /usr/bin/genmk /usr/bin/sor
	create_link /usr/include/pccts "$WINAME/include"
	chmod_wi "$WINAME"
}

# Создание псевдомодуля lexyacc
install_lexyacc()
{
	WINAME='lexyacc_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.lexyacc" "$WINAME/rules.cvslvk"
	chmod_wi "$WINAME"
}

# Cоздание псевдомодуля для X11
# На платформе linux ставим WI для совместимости
install_X()
{
	WINAME='X_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.x11" "$WINAME/rules.cvslvk"
	chmod_wi "$WINAME"
}

install_Glib2()
{
	WINAME='GLib2_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.Glib2" "$WINAME/rules.cvslvk"
	create_links "$WINAME/include" /usr/include/glib-2.0/* /usr/lib/glib-2.0/include/*
	create_links "$WINAME/lib" /usr/lib/libglib-2.0.* /usr/lib/libgmodule-2.0.* /usr/lib/libgobject-2.0.* /usr/lib/libgthread-2.0.* /usr/lib/libgio-2.0.*
	chmod_wi "$WINAME"
}

install_Qt3()
{
	WINAME='Qt3_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.qt3" "$WINAME/rules.cvslvk"
	create_link /usr/include/qt3 "$WINAME/include"
	create_links "$WINAME/bin" /usr/bin/lrelease-qt3 /usr/bin/lupdate-qt3 /usr/bin/moc-qt3 /usr/bin/uic-qt3
	create_links "$WINAME/lib" /usr/lib/libqt-mt.so /usr/lib/libqt-mt.so.3
	chmod_wi "$WINAME"
}

install_Qt4()
{
	WINAME='Qt4_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.qt4" "$WINAME/rules.cvslvk"
	create_link /usr/include/qt4 "$WINAME/include"
	create_links "$WINAME/bin" /usr/bin/lrelease-qt4 /usr/bin/lupdate-qt3 /usr/bin/moc-qt4 /usr/bin/uic-qt4 /usr/bin/rcc;
	create_links "$WINAME/lib" /usr/lib/libQt*
	chmod_wi "$WINAME"
}

install_xml2()
{
	WINAME='xml2_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.xml2" "$WINAME/rules.cvslvk"
	create_link /usr/include/libxml2 "$WINAME/include"
	create_links "$WINAME/lib" /usr/lib/libxml2*
	chmod_wi "$WINAME"
}

install_qwt()
{
	WINAME='qwt_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.qwt" "$WINAME/rules.cvslvk"
	create_link /usr/include/qwt "$WINAME/include"
	create_links "$WINAME/lib" /usr/lib/libqwt*
	chmod_wi "$WINAME"
}

install_qwt_qt3()
{
	WINAME='qwt_'$ARCH
	create_wi "$WINAME"
	cp "$SOURCE/rules.cvslvk.qwt-qt3" "$WINAME/rules.cvslvk"
	create_link /usr/include/qwt-qt3 "$WINAME/include"
	create_links "$WINAME/lib" /usr/lib/libqwt*
	chmod_wi "$WINAME"
}

SOURCE=$(pwd)
ARCH="$("$SOURCE/cvslvk" get_arch)-$("$SOURCE/cvslvk" get_os)"
cd "$CL_DIR"

install_pccts
install_lexyacc
install_X
install_Glib2
install_Qt3
install_Qt4
install_xml2
if [ -d /usr/include/qwt ]; then
	install_qwt
elif [ -d /usr/include/qwt-qt3 ]; then
	install_qwt_qt3
fi
