#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 SOURCE TARGET"
  echo "  SOURCE  original CVSLVK directory"
  echo "  TARGET  where new CVSLVK directory should be created"
  exit 1
fi

SOURCE="$1"
TARGET="$2"

if [ x"$SOURCE" = x"$TARGET" ]; then
  echo "SOURCE and TARGET directories should be different."
  echo "Aborting now."
  exit 1
fi

test -d "$TARGET" || mkdir "$TARGET"
if [ ! -d "$TARGET" ]; then
  echo "Failed to create $TARGET directory."
  echo "Aborting now."
  exit 1
fi

list="cppargs.awk getppid.awk cvslvk liborder.awk Makefile.cvslvk \
      process_wi.awk `cd $SOURCE && echo *_x86-linux*/`"

cd "$TARGET"
for i in $list; do ln -s "$SOURCE/$i" .; done

CL_DIR="$TARGET" cvslvk make_rules

echo "CVSLVK directory set up at $TARGET."
echo "Now you can add your own CVSLVK modules."
exit 0
