#!/bin/sh
set -e

CLGROUP=stand

create_wi()
{
	local WINAME="$1"
	mkdir "$CL_DIR/$WINAME"
	touch "$CL_DIR/$WINAME"/REMOVE_ON_CVSLVK_UPDATE
	touch "$CL_DIR/$WINAME"/NOREMOVE
}

delete_wi()
{
	local WINAME="$1"
	rm -rf "$CL_DIR/$WINAME"
}

chmod_wi()
{
	WINAME="$1"
	clgroup=$(ls -Lld "$CL_DIR" | awk '{print($4)}')
	test "$clgroup" = "$CLGROUP"||return 0
	chgrp -R "$CLGROUP" "$CL_DIR/$WINAME"
	chmod -R g+rw "$CL_DIR/$WINAME"
}

create_link()
{
	local LINK="$1"
	local TARGET="$2"
	if [ -e "$TARGET" ]; then
		ln -s "$TARGET" "$LINK"
	else
		echo "Warning: $TARGET not found." >&2
	fi

}

create_links()
{
	local DIR="$1"
	shift 1

	test -d "$DIR" || mkdir "$DIR"
	for TARGET in "$@"; do
		create_link "$DIR" "$TARGET"
	done
}

SOURCE=$(pwd)
ARCH="$("../cvslvk" get_arch)-$("../cvslvk" get_os)"

for FILE in *.rules; do
	NAME="$(basename "$FILE" .rules)"
	WINAME="${NAME}_${ARCH}"
	create_wi "$WINAME"
	cd "$CL_DIR/$WINAME"
	cp "$SOURCE/$FILE" rules.cvslvk
	if [ -e "$SOURCE/$NAME.install" ];then
		if ! ( . "$SOURCE/$NAME.install" );then
			cd "$SOURCE"
			delete_wi "$WINAME"
			continue
		fi
	fi
	chmod_wi "$WINAME"
done
