create_link include /usr/include/qt4
create_links bin /usr/bin/lrelease-qt4 /usr/bin/moc-qt4 /usr/bin/uic-qt4 /usr/bin/rcc;
if [ -e /usr/lib/i386-linux-gnu ];then
	BASE=/usr/lib/i386-linux-gnu
elif [ -e /usr/lib/x86_64-linux-gnu ];then
	BASE=/usr/lib/x86_64-linux-gnu
else
	BASE=/usr/lib
fi
create_links lib ${BASE}/libQt*

if [ -e ${BASE}/qt5/bin/lupdate ];then
	create_link bin/lupdate ${BASE}/qt5/bin/lupdate
else
	create_link bin/lupdate /usr/bin/lupdate-qt4
fi
