if [ -e /usr/lib/i386-linux-gnu ];then
	GNU_DIR=i386-linux-gnu
elif [ -e /usr/lib/x86_64-linux-gnu ];then
	GNU_DIR=x86_64-linux-gnu
fi

create_links bin /usr/lib/${GNU_DIR}/qt5/bin/uic /usr/lib/${GNU_DIR}/qt5/bin/moc /usr/lib/${GNU_DIR}/qt5/bin/rcc /usr/lib/${GNU_DIR}/qt5/bin/lrelease /usr/lib/${GNU_DIR}/qt5/bin/lupdate

create_links include /usr/include/${GNU_DIR}/qt5/*
create_links lib /usr/lib/${GNU_DIR}/libQt5*
